# Numpy arrays

# Aggregate functions

In [32]:
import numpy as np

In [33]:
L=np.random.randint(10,100,40)
L

array([98, 24, 27, 71, 78, 83, 90, 78, 72, 50, 42, 59, 27, 31, 31, 27, 89,
       86, 76, 46, 30, 85, 22, 87, 96, 50, 77, 11, 93, 24, 16, 66, 79, 14,
       87, 84, 83, 91, 87, 87])

In [34]:
np.sum(L)

2454

In [35]:
np.max(L)

98

In [36]:
M=np.random.randint(0,10,(3,3))
M

array([[2, 6, 6],
       [4, 4, 5],
       [4, 8, 2]])

In [37]:
np.sort(M,axis=0)

array([[2, 4, 2],
       [4, 6, 5],
       [4, 8, 6]])

In [38]:
np.argsort(M,axis=0)

array([[0, 1, 2],
       [1, 0, 1],
       [2, 2, 0]], dtype=int64)

In [39]:
np.max(M,axis=1)

array([6, 5, 8])

In [40]:
np.median(M)

4.0

In [41]:
np.mean(M)

4.555555555555555

In [42]:
np.average(M)

4.555555555555555

In [43]:
np.std(M)

1.8324913891634047

In [44]:
np.mean(M,axis=1)

array([4.66666667, 4.33333333, 4.66666667])

# Indexing and sorting

In [55]:
M

array([[2, 6, 6],
       [4, 4, 5],
       [4, 8, 2]])

In [58]:
M

array([[2, 6, 6],
       [4, 4, 5],
       [4, 8, 2]])

In [64]:
a=np.array([1,3,5,7,9])
np.where(a<4)  #returns the array of integer indices where the condition is satisfied

(array([0, 1], dtype=int64),)

# Structured Numpy Array

In [84]:
import numpy as np
arr=np.array([(1,'Rolex',168.6),(2,'Dilli',180.3)],dtype=[('ID','i4'),('Name','U20'),('Height','f8')])
arr

array([(1, 'Rolex', 168.6), (2, 'Dilli', 180.3)],
      dtype=[('ID', '<i4'), ('Name', '<U20'), ('Height', '<f8')])

In [86]:
'''Structured Numpy array is similar to struct to C it is overall an user defined array in numpy where the datatypes of the attributes are specified by user'''

'Structured Numpy array is similar to struct to C it is overall an user defined array in numpy where the datatypes of the attributes are specified by user'

# Comparision,Masks and Boolean Arrays

In [3]:
import numpy as np
sales=[10,20,30,40,35,38,46,54,50,68,60,60]
arr=np.array(sales)
arr

array([10, 20, 30, 40, 35, 38, 46, 54, 50, 68, 60, 60])

In [6]:
arr[arr>40]

array([46, 54, 50, 68, 60, 60])

In [7]:
#Boolean masking or boolean indexing is a feature in Python NumPy that allows for the filtering of values in numpy arrays.

In [12]:
x=arr>4
x

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [14]:
np.all(x)

True

# Fancy Indexing  && Slicing

In [46]:
#fancy indexing is the concept of accesing elements through an array of indexes

In [47]:
arr

array([10, 20, 30, 40, 35, 38, 46, 54, 50, 68, 60, 60])

In [48]:
idx=[0,2,4,-1]
arr[idx]

array([10, 30, 35, 60])

In [49]:
a = np.array([[1 ,2 ],[3 ,4 ],[5 ,6 ]])
a[[0 ,1 ,2 ],[0 ,0 ,1]]

array([1, 3, 6])

In [93]:
rand=np.random.RandomState(42)
x=rand.randint(0,2,(9,9))
x

array([[0, 1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 1, 0, 1, 1],
       [1, 0, 1, 0, 1, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 1, 1, 1, 0],
       [1, 0, 0, 0, 0, 0, 1, 1, 1],
       [1, 1, 0, 1, 1, 0, 1, 0, 1],
       [0, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 1, 1, 1, 1],
       [0, 1, 0, 1, 1, 1, 0, 1, 0]])

In [94]:
np.all(x)

False

In [95]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [96]:
a*3

array([[ 3,  6],
       [ 9, 12],
       [15, 18]])

In [97]:
a**2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]], dtype=int32)

In [98]:
a+a**2

array([[ 2,  6],
       [12, 20],
       [30, 42]])

In [105]:
r=np.ones((2,2),dtype='i4')
r

array([[1, 1],
       [1, 1]])

In [114]:
p=np.ones((2,2),dtype={'names':('Att1','Att2'),'formats':('int','f8')})
p

array([[(1, 1.), (1, 1.)],
       [(1, 1.), (1, 1.)]], dtype=[('Att1', '<i4'), ('Att2', '<f8')])

In [117]:
q=np.zeros((2,3),dtype={'names':('id','name','age'),'formats':('i4','U20','i4')})  #structured numpy array
q

array([[(0, '', 0), (0, '', 0), (0, '', 0)],
       [(0, '', 0), (0, '', 0), (0, '', 0)]],
      dtype=[('id', '<i4'), ('name', '<U20'), ('age', '<i4')])

In [136]:
c=np.arange(8).reshape(2,2,2)
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [20]:
#structured numpy array
import numpy as np
arr=np.array([(1,'Rolex'),(2,'Dilli')],dtype=[('ID','i4'),('NAME','U20')])
arr

array([(1, 'Rolex'), (2, 'Dilli')],
      dtype=[('ID', '<i4'), ('NAME', '<U20')])

In [37]:
l=[1,4,3]
l2=[3,4]
a=np.array(l)
b=np.array(l2)
print(a)
print(b)

[1 4 3]
[3 4]


In [34]:
b>0

array([ True,  True])

In [45]:
a>2

array([False,  True,  True])

In [46]:
a[a>2]

array([4, 3])

In [58]:
#creating a random numpy array
rand=np.random.RandomState(0)
a=rand.randn(2,2)  #creates an random valued numpy array with given shape 
a

array([[1.76405235, 0.40015721],
       [0.97873798, 2.2408932 ]])

In [67]:
a=rand.rand(4) #creates a numpy array with specified shape but the conatining values are from 0 to 1
a

array([0.97749514, 0.87650525, 0.33815895, 0.96157015])

In [84]:
x=np.random.randint(-5,10,(5,2))
x

array([[ 0, -3],
       [-3,  8],
       [-5,  1],
       [-5,  9],
       [ 9,  5]])

In [80]:
y=np.arange(1,11).reshape(5,2)
y

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])